// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKSSu8bjOJzF169uxNzyvP4oQS1mApy00',
    appId: '1:118492027388:web:3023a4aab2b77ec921ba79',
    messagingSenderId: '118492027388',
    projectId: 'reddit-clone-d7b17',
    authDomain: 'reddit-clone-d7b17.firebaseapp.com',
    storageBucket: 'reddit-clone-d7b17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFSqeNrYdPO51pI7h8kSiV6EsLoxnghn4',
    appId: '1:118492027388:android:4df5c7d08d53d3c421ba79',
    messagingSenderId: '118492027388',
    projectId: 'reddit-clone-d7b17',
    storageBucket: 'reddit-clone-d7b17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASjMJTL81E-ahBrs-uCIoGABHvusnwK9o',
    appId: '1:118492027388:ios:03f5b11796a7438b21ba79',
    messagingSenderId: '118492027388',
    projectId: 'reddit-clone-d7b17',
    storageBucket: 'reddit-clone-d7b17.appspot.com',
    iosClientId: '118492027388-j9def61pfqcsol9q4h4rvcn03ikrpq1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASjMJTL81E-ahBrs-uCIoGABHvusnwK9o',
    appId: '1:118492027388:ios:03f5b11796a7438b21ba79',
    messagingSenderId: '118492027388',
    projectId: 'reddit-clone-d7b17',
    storageBucket: 'reddit-clone-d7b17.appspot.com',
    iosClientId: '118492027388-j9def61pfqcsol9q4h4rvcn03ikrpq1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
